name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # ------------ LINT CHECKS ------------
    - name: Set up Node.js (for React)
      if: exists('package.json')
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Python (for Python)
      if: exists('requirements.txt')
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and Lint (React)
      if: exists('package.json')
      run: |
        npm install
        npx eslint . --ext .js,.jsx,.ts,.tsx || true

    - name: Install and Lint (Python)
      if: exists('requirements.txt')
      run: |
        pip install flake8
        flake8 . || true

    # ------------ DOCKER LOGIN ------------
    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # ------------ BUILD AND PUSH IMAGE ------------
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest
